#try-except
try:
    result=10/0
except:
    print('something went wrong' )

try:
    num = int("8")
except ValueError:
    print("Invalid number!")

